name: jak_doczlapie
description: "A new Flutter project."
publish_to: "none"
version: 1.0.1+1

environment:
  sdk: 3.9.2
  flutter: "3.35.5"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  riverpod: ^3.0.1
  hooks_riverpod: ^3.0.1
  flutter_hooks: ^0.21.3+1
  riverpod_annotation: ^3.0.1
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  auto_route: ^10.1.2
  freezed: ^3.2.3
  freezed_annotation: ^3.1.0
  image_picker: ^1.2.0
  flutter_form_builder: ^10.2.0
  form_builder_validators: ^11.2.0
  device_preview: ^1.1.0
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  dio: ^5.9.0
  retrofit: ^4.7.3
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.7.1
  riverpod_generator: ^3.0.0
  auto_route_generator: ^10.2.4
  solvro_config: ^1.1.1
  retrofit_generator: ^10.0.0
  json_serializable: ^6.11.1

flutter:
  uses-material-design: true

lint_staged:
  "lib/**.dart": dart format && dart fix --apply
